language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=tests
  matrix:
    - LISP=sbcl-bin COVERALLS=true REVIEWDOG=true
    - LISP=ccl-bin
    - LISP=abcl-bin

addons:
  apt:
    packages:
      - default-jre

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install Rudolph-Miller/jonathan
  - ros install fukamachi/lack
  - ros install fukamachi/assoc-utils
  - ros install prove
  - if [ "$REVIEWDOG" ]; then ros install fukamachi/sblint; fi

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - run-prove linebot-tests.asd
  - if [ "$REVIEWDOG" ]; then sblint-reviewdog; fi
